"""Import Alex Cooper's 40 ad creative template prompts into the library.

Source: https://adcrate.notion.site/Nano-Banana-2-Prompt-Document
Credit: Alex Cooper / Adcrate. Original Claude prompts by Will Sartorius.

Run: python scripts/import_cooper_templates.py
"""

from pathlib import Path
import yaml

OUTPUT_DIR = Path("prompts/library/cooper")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SOURCE = "Alex Cooper / Adcrate (adcrate.notion.site)"

TEMPLATES = [
    {
        "id": "cooper-01-headline",
        "name": "Headline",
        "category": "headline",
        "description": "Bold headline ad. Tests text rendering. If this comes back clean, the model handles copy.",
        "product_types": ["any"],
        "audience_fit": ["problem_aware", "solution_aware", "product_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["4:5", "1:1"],
        "tags": ["headline", "bold-statement", "text-heavy", "scroll-stopper"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact product colors, typography style, and brand tone precisely. Create: a static ad with a [BACKGROUND] background. Top third: large bold sans-serif headline reading "[YOUR HEADLINE, under 10 words]". Below in smaller text: "[YOUR SUBHEAD, one sentence]". Bottom half: [YOUR PRODUCT] on the surface with [DETAILS]. Shot at 50mm f/2.8 from slightly above. [BRAND] logo bottom right. Clean, authoritative. 4:5 aspect ratio.',
    },
    {
        "id": "cooper-02-offer",
        "name": "Offer/Promotion",
        "category": "offer",
        "description": "Promotional ad with split background. The money-maker. Test your core offer.",
        "product_types": ["any"],
        "audience_fit": ["product_aware", "most_aware"],
        "funnel_stage": "conversion",
        "aspect_ratios": ["9:16", "4:5"],
        "tags": ["offer", "promotion", "discount", "split-background", "conversion"],
        "template_prompt": 'Use the attached images as brand reference. Match exact brand colors and typography style. Create: a promotional ad with a split background. Top 60% is [PRIMARY BRAND COLOR] and bottom 40% is [CONTRAST COLOR like warm cream]. [YOUR PRODUCT] sits centered where colors meet, soft studio lighting. Upper area: large [CONTRAST TEXT] sans-serif reading "[YOUR OFFER like YOUR FIRST MONTH FREE]". Below: "[OFFER DETAILS]". Lower section: small [BRAND COLOR] text with [VALUE ADDS]. [BRAND] logo bottom right. 9:16 aspect ratio.',
    },
    {
        "id": "cooper-03-testimonials",
        "name": "Testimonials",
        "category": "testimonial",
        "description": "Real environments + text overlays. Tests composition depth.",
        "product_types": ["any"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["9:16", "4:5"],
        "tags": ["testimonial", "review", "social-proof", "lifestyle", "trust"],
        "template_prompt": 'Use the attached images as brand reference. Create: a testimonial ad set in [SETTING like bright bathroom / kitchen] with warm natural light. [YOUR PRODUCT] on [SURFACE], slightly out of focus. Overlaid: large bold white sans-serif "[SHORT HEADLINE]". Below: "[FULL QUOTE 2-3 sentences]. [NAME], [CREDENTIAL]." Five filled [BRAND COLOR] stars. [BRAND] logo bottom right in white. Shot on 35mm f/2.0. 9:16 aspect ratio.',
    },
    {
        "id": "cooper-04-features-benefits",
        "name": "Features/Benefits Point-Out",
        "category": "educational",
        "description": "Educational diagram-style layout with callout boxes.",
        "product_types": ["any"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["4:5", "1:1"],
        "tags": ["features", "benefits", "educational", "diagram", "callouts"],
        "template_prompt": 'Use the attached images as brand reference. Create: an educational diagram-style ad on white background. Top: bold [BRAND COLOR] text "[HEADER like What Makes [PRODUCT] Different]". Below: [YOUR PRODUCT] centered, even studio lighting. Four callout boxes with connecting lines: "[BENEFIT 1-4]". Each has a small [BRAND COLOR] circle. "[WEBSITE]" bottom center. [BRAND] logo bottom right. Scientific diagram redesigned by a luxury agency. 4:5 aspect ratio.',
    },
    {
        "id": "cooper-05-bullet-points",
        "name": "Bullet-Points",
        "category": "benefits",
        "description": "Split composition. Product left, benefits right.",
        "product_types": ["any"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["4:5", "1:1"],
        "tags": ["bullets", "benefits", "split-layout", "clean"],
        "template_prompt": 'Use the attached images as brand reference. Create: a benefit-list ad, split composition on [BACKGROUND] background. Left 40%: [YOUR PRODUCT] on [SURFACE], shot at 85mm f/2.8. Right 60%: vertical stack of five lines with filled [BRAND COLOR] circles: "[BENEFIT 1-5]". Clean sans-serif, generous spacing. [BRAND] logo bottom right. 4:5 aspect ratio.',
    },
    {
        "id": "cooper-06-social-proof",
        "name": "Social Proof",
        "category": "social-proof",
        "description": "Member count + review card + press logos. The trust stack.",
        "product_types": ["any"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["4:5", "1:1"],
        "tags": ["social-proof", "reviews", "press", "trust", "authority"],
        "template_prompt": 'Use the attached images as brand reference. Create: a social proof ad on [BACKGROUND like warm cream]. Top: "[HEADLINE like Join 1,000,000+ Members]" in bold [BRAND COLOR]. Five filled stars with "Rated [X] out of 5". Center: [YOUR PRODUCT] at 50mm f/4. Below: frosted white card with five-star rating, "[REVIEW TITLE]", "[2-3 SENTENCE REVIEW]", "[ATTRIBUTION]" in italic. Below card: "As Featured In" with five grayscale logos. [BRAND] logo bottom right. 4:5 aspect ratio.',
    },
    {
        "id": "cooper-07-us-vs-them",
        "name": "Us vs Them",
        "category": "comparison",
        "description": "Side-by-side comparison. Photography quality gap IS the argument.",
        "product_types": ["any"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["4:5", "1:1"],
        "tags": ["comparison", "vs", "competitive", "split-screen", "trust"],
        "template_prompt": 'Use the attached images as brand reference. Create: a side-by-side divided vertically. Left: muted gray-blue background. Right: [PRIMARY BRAND COLOR]. Center top: white circle with "VS". Left header: "[COMPETITOR CATEGORY]" + generic competitor product + list with X marks: "[WEAKNESS 1-5]". Right header: "[YOUR BRAND]" + [YOUR PRODUCT] + list with checkmarks: "[STRENGTH 1-5]". [BRAND] logo bottom right. 4:5 aspect ratio.',
    },
    {
        "id": "cooper-08-before-after-ugc",
        "name": "Before & After (UGC Native)",
        "category": "ugc",
        "description": "Mirror selfie transformation. Must look like a real person posted it.",
        "product_types": ["beauty", "supplement", "fitness", "health"],
        "audience_fit": ["problem_aware", "solution_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["9:16"],
        "tags": ["ugc", "before-after", "transformation", "authentic", "tiktok-native"],
        "template_prompt": 'Use the attached images as brand reference for product color ONLY. This should look like a real person\'s post. Create: TikTok before-and-after. LEFT: grainy iPhone mirror selfie, [PERSON] in dimly lit bathroom, [BEFORE STATE], harsh lighting. White handwritten text: "[BEFORE DATE]". RIGHT: same person, same bathroom, bright natural light, [AFTER STATE], [PRODUCT] visible on counter. White text: "[AFTER DATE]". Top center: "[TIMEFRAME] on [BRAND]" with emoji. Should look stitched in CapCut. 9:16 aspect ratio.',
    },
    {
        "id": "cooper-09-negative-marketing",
        "name": "Negative Marketing (Bait & Switch)",
        "category": "scroll-stopper",
        "description": "Fake bad review that is actually a rave. Scroll-stopper.",
        "product_types": ["any"],
        "audience_fit": ["unaware", "problem_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["4:5", "1:1"],
        "tags": ["bait-switch", "scroll-stopper", "review", "curiosity", "native"],
        "template_prompt": 'Use the attached images as brand reference. Create: Background is close-up of [PRODUCT], slightly blurred. Center: white rounded-rectangle review card (Amazon-style). Gray user icon, "[NAME]", one gold star + four gray, orange "Verified Purchase" badge, bold text: "[BAIT that sounds negative but is positive]". Bottom: bold white sans-serif "[PUNCHLINE like THE REVIEWS ARE IN.]". [BRAND] logo bottom right. 4:5 aspect ratio.',
    },
    {
        "id": "cooper-10-press-editorial",
        "name": "Press/Editorial",
        "category": "editorial",
        "description": "Authority play. Vogue back-page energy.",
        "product_types": ["any"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["4:5", "1:1"],
        "tags": ["press", "editorial", "authority", "premium", "trust"],
        "template_prompt": 'Use the attached images as brand reference. Create: a press ad on off-white linen background. Top: "As Featured In" in small [BRAND COLOR] uppercase wide-tracked text. Below: five grayscale publication logos. Center: italic serif pull-quote in [BRAND COLOR]: "[PRESS QUOTE]" with attribution. Lower third: [PRODUCT] at 85mm f/2.8, soft side light. [BRAND] logo bottom left. Generous white space. Full-page Vogue energy. 4:5 aspect ratio.',
    },
    {
        "id": "cooper-11-pull-quote-review",
        "name": "Pull-Quote Review Card",
        "category": "social-proof",
        "description": "Emotional quote headline over truncated review card. The Read more creates an open loop.",
        "product_types": ["any"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["1:1", "4:5"],
        "tags": ["review", "pull-quote", "open-loop", "curiosity", "trust"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact product colors and brand tone precisely. Create: a review-driven ad with a solid [BRAND COLOR with hex] color block background filling the entire image. Top half: large bold italic serif text in white with curly quotation marks reading "[PULL-QUOTE — the most emotional 4-8 word phrase from the review]". Directly below the quote: five large filled gold/yellow star icons in a horizontal row. Bottom left, overlapping the color background: a white rounded-corner review card with subtle shadow, containing: a small gray circular default avatar icon, beside it "[FIRST NAME + LAST INITIAL]" in bold dark sans-serif with a small [FLAG EMOJI], below the name a blue checkmark icon with "[VERIFIED REVIEWER]" in small blue text. Below the reviewer info: the review body text in medium-weight dark sans-serif, 4-6 lines that trails off mid-sentence, ending with "...Read more" in bold [BRAND COLOR] text. Below the review text: "Was this review helpful?" in small gray text with a thumbs-up icon and "[HELPFULNESS COUNT]" beside it. Bottom right, overlapping both the card and the color background: [YOUR PRODUCT] angled slightly toward the viewer. 1:1 or 4:5 aspect ratio.',
    },
    {
        "id": "cooper-13-stat-surround",
        "name": "Stat Surround / Callout Radial",
        "category": "product-hero",
        "description": "Product is the sun. Stats are the planets. Arrows make it scannable in under 2 seconds.",
        "product_types": ["food", "beverage", "supplement"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["1:1"],
        "tags": ["stats", "callouts", "radial", "product-hero", "data-driven"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact product design, colors, and typography style precisely. Create: a static ad on a white-to-[LIGHT GRADIENT COLOR] gradient background. Top: large bold [TEXT COLOR] sans-serif headline reading "[HEADLINE]". Center: [YOUR PRODUCT] on white background, soft studio lighting. Floating near the product: a small circular badge reading "[PRICE POINT]" in [BADGE COLOR]. Flanking the product on both sides: four stat callouts with curved arrows pointing toward the product. Left side: "[STAT 1]" with "[LABEL]", "[STAT 2]" with "[LABEL]". Right side: "[STAT 3]" with "[LABEL]", "[STAT 4]" with "[LABEL]" and five filled gold stars beneath. Arrows are simple hand-drawn-style curved lines. No brand logo. Clean, informational, appetizing. 1:1 aspect ratio.',
    },
    {
        "id": "cooper-15-social-comment",
        "name": "Social Comment Screenshot + Product",
        "category": "social-proof",
        "description": "Screenshotted comment = instant credibility. Looks organic.",
        "product_types": ["any"],
        "audience_fit": ["problem_aware", "solution_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["1:1"],
        "tags": ["social-comment", "screenshot", "native", "organic", "trust"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact product design and colors precisely. Create: a static ad on a clean white background. Top: oversized bold black sans-serif headline reading "[HOOK HEADLINE]" with [EMOJI] at the end. Center: a social media comment card with light gray rounded-rectangle background containing: a small circular profile avatar (top left), bold name "[REVIEWER NAME]", and a multi-sentence review in regular-weight sans-serif: "[FULL REVIEW TEXT, 3-4 sentences, conversational and emotional]". Small gray timestamp "[TIMESTAMP like 2d]" below the comment. Bottom center: [YOUR PRODUCT] photographed at a slight angle on white, soft studio lighting. No brand logo. No stars. The rawness is the point. 1:1 aspect ratio.',
    },
    {
        "id": "cooper-16-curiosity-gap",
        "name": "Curiosity Gap / Hook Quote Testimonial",
        "category": "scroll-stopper",
        "description": "Provocative headline forces the double-take. The reveal reframes it. Scroll-stop machine.",
        "product_types": ["any"],
        "audience_fit": ["unaware", "problem_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["1:1"],
        "tags": ["curiosity-gap", "bait-switch", "scroll-stopper", "testimonial", "hook"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact product design, colors, and typography style precisely. Create: a static ad on a clean white background. Top center: large [ACCENT COLOR] opening quotation marks. Below: mixed-weight headline in black — the first line in italic serif reading "[SETUP LINE]", the next two lines in enormous heavy-weight bold all-caps sans-serif reading "[BAIT PHRASE]", followed by a smaller sentence-case line reading "[REVEAL]". Closing quotation marks and "[ATTRIBUTION]" in regular weight. Left side bottom: [YOUR PRODUCT] at a slight angle with [PRODUCT DETAILS]. To the left of the product: a [TRUST BADGE]. Right side bottom: [NUMBER] filled [ACCENT COLOR] stars and bold text reading "[REVIEW COUNT] 5-Star Reviews". 1:1 aspect ratio.',
    },
    {
        "id": "cooper-20-advertorial",
        "name": "Advertorial / Editorial Content Card",
        "category": "editorial",
        "description": "Looks like a news post, not an ad. Designed to blend into feed.",
        "product_types": ["any"],
        "audience_fit": ["unaware", "problem_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["4:5"],
        "tags": ["advertorial", "editorial", "native", "feed-blend", "authority"],
        "template_prompt": 'Use the attached images as brand reference for tone ONLY. Do NOT use polished ad layouts. This should look like organic editorial content. Create: a full-bleed moody portrait photo of [PERSON DESCRIPTION], warm amber-toned lighting, shot on 50mm f/1.8, shallow depth of field, cinematic color grade. Lower 45% is a text overlay zone: a prominent white rounded-rectangle pill label reading "[CATEGORY TAG like HOT TOPIC]" in centered uppercase sans-serif. Below: very large, dominant, bold all-caps condensed sans-serif headline in white text with key words in [HIGHLIGHT COLOR]: "[HEADLINE like [BRAND] IS BLOWING UP ON TIKTOK]". The headline should be oversized. Bottom center: "[@HANDLE]" in small white text. No product shot, no CTA button, no stars. 4:5 aspect ratio.',
    },
    {
        "id": "cooper-22-flavor-story",
        "name": 'Flavor Story / "Tastes Like"',
        "category": "product-hero",
        "description": "Flavor visualization. Background IS the taste. Product is the payoff.",
        "product_types": ["food", "beverage"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["1:1"],
        "tags": ["flavor", "food", "indulgent", "lifestyle", "appetite-appeal"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact product design, colors, and packaging precisely. Create: a flavor-visualization ad. Full background is a photorealistic close-up food scene of [INDULGENT FOOD]. Shot at 50mm f/2.8, shallow depth of field, warm bakery lighting. Top third: large bold white sans-serif headline reading "[HEADLINE like A protein bar that tastes like...]" with one key word in bold italic. [YOUR PRODUCT] placed bottom-right, angled 15 degrees. Bottom: semi-transparent white bar with three stat columns: "[STAT 1]" | "[STAT 2]" | "[STAT 3]". Very bottom: "[CLEAN LABEL CLAIM]". Food is the hero — product is the payoff. 1:1 aspect ratio.',
    },
    {
        "id": "cooper-25-us-vs-them-color",
        "name": "Us vs. Them Color Split",
        "category": "comparison",
        "description": "Color-split comparison. Your brand color vs muted competitor side.",
        "product_types": ["food", "beverage", "supplement", "beauty"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["1:1"],
        "tags": ["comparison", "vs", "color-split", "checkmarks", "competitive"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact product design and colors precisely. Create: a side-by-side comparison ad divided vertically. Left half: [PRIMARY BRAND COLOR] background. [YOUR PRODUCT] photographed with dynamic energy — [ACTION DETAIL]. Brand logo in bold white upper-left. Below product: vertical stack of 4 benefits with green circle checkmarks: "[STRENGTH 1-4]" in bold white uppercase. Right half: [CONTRAST COLOR like pale cream] background. Generic unbranded competitor product [DESCRIPTION]. Header: "[COMPETITOR CATEGORY]" in dark text. Below: vertical stack of 4 weaknesses with red circle X marks: "[WEAKNESS 1-4]" in bold dark uppercase. Center divider: a comic-style "VS" burst graphic. 1:1 aspect ratio.',
    },
    {
        "id": "cooper-29-ugc-viral-post",
        "name": "UGC + Viral Post Overlay",
        "category": "ugc",
        "description": "Casual selfie with a Reddit/Twitter post screenshot overlaid. Looks completely organic.",
        "product_types": ["any"],
        "audience_fit": ["unaware", "problem_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["9:16"],
        "tags": ["ugc", "viral", "reddit", "twitter", "organic", "native", "scroll-stopper"],
        "template_prompt": 'Use the attached images as brand reference for product color ONLY. Do NOT use ad layouts or polish. This should look completely native and organic. Create: a casual selfie of [PERSON like a man in mid-20s, beanie, crewneck] doing something mundane [ACTION like brushing teeth, making coffee]. iPhone front camera, slightly grainy, bathroom/kitchen lighting, no professional setup. Overlaid in the center: a realistic screenshot of a [PLATFORM like Reddit / Twitter / X] post. [POST DETAILS like subreddit name, username, timestamp, upvote count]. Post title in bold: "[PROVOCATIVE OPINION HEADLINE]". Post body: "[2-3 sentences expanding on the opinion]". The post should feel like the person is reacting to it. No product visible. No brand logo. No CTA. The hook is the opinion. 9:16 aspect ratio.',
    },
    {
        "id": "cooper-31-comparison-grid",
        "name": "Comparison Grid / Table",
        "category": "comparison",
        "description": "Structured comparison grid. Meme-format that goes viral on X or Reddit.",
        "product_types": ["food", "beverage", "supplement", "beauty"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["1:1"],
        "tags": ["comparison", "grid", "table", "meme-format", "viral"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact product packaging precisely. Create: a structured comparison grid ad on white background. Top row divided 50/50: Left: [YOUR PRODUCT] packaging on white. Right: [COMPETITOR PRODUCT] packaging on white. Below: three horizontal rows spanning full width, each divided 50/50. Each row compares one attribute: Row 1: "[YOUR ADVANTAGE]" vs "[COMPETITOR WEAKNESS]". Row 2: "[YOUR ADVANTAGE]" vs "[COMPETITOR WEAKNESS]". Row 3: "[YOUR ADVANTAGE]" vs "[COMPETITOR WEAKNESS]". All text in bold black serif or heavy sans-serif. No icons, no colors, no checkmarks — the copy contrast does the work. Should feel like a meme-format comparison. 1:1 aspect ratio.',
    },
    {
        "id": "cooper-33-faux-press",
        "name": "Faux Press / News Articles Screenshot",
        "category": "editorial",
        "description": "Looks like a real online news article screenshot. Authority through publication mastheads.",
        "product_types": ["any"],
        "audience_fit": ["unaware", "problem_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["4:5"],
        "tags": ["press", "news", "faux", "authority", "editorial", "native"],
        "template_prompt": 'Use the attached images as brand reference. Create: a static ad designed to look like a real online news article screenshot. Top 25%: white background with a realistic major publication masthead in large bold black serif text [PUBLICATION STYLE]. Below: thin gray rule. Small gray text "Latest Headlines". Then: bold black serif headline: "[HEADLINE like The $[PRICE] [PRODUCT CATEGORY] with over [NUMBER] five-star reviews]". Bottom 60%: two side-by-side casual UGC-style photos of [PEOPLE] each holding [YOUR PRODUCT] in a casual selfie pose. Photos should look like real customer submissions. No brand logo. No CTA. Should look like an organic article screenshot. 4:5 aspect ratio.',
    },
    {
        "id": "cooper-34-faux-iphone-notes",
        "name": "Faux iPhone Notes / App Screenshot",
        "category": "native",
        "description": "Disguised as an iPhone Notes app screenshot. Blends into feed completely.",
        "product_types": ["supplement", "health", "beauty", "food"],
        "audience_fit": ["problem_aware", "solution_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["1:1"],
        "tags": ["faux", "iphone", "notes", "native", "feed-blend", "trust"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact product design and packaging precisely. Create: a static ad disguised as an iPhone Notes app screenshot. Top: realistic iOS status bar (time "[TIME]", signal bars, wifi icon, battery icon). Below: iOS Notes navigation — blue "< All iCloud" back arrow left, share icon right. Below nav: small gray timestamp text "[DATE]". Main content area on white background: bold black serif headline "[HEADLINE like In Just [DOSAGE] A Day]". Below: [3 BENEFIT ROWS], each with a [BRAND COLOR] filled circle checkmark + [EMOJI] + bold black text: "[BENEFIT 1-3]". Right side, overlapping the benefit text slightly: [YOUR PRODUCT] at a slight angle with details. Clean white background throughout. 1:1 aspect ratio.',
    },
    {
        "id": "cooper-40-post-it-note",
        "name": "Native / Ugly Post-It Note Style",
        "category": "native",
        "description": "Ugly-on-purpose. Product hero with handwritten post-it note. Blends into feed as organic content.",
        "product_types": ["any"],
        "audience_fit": ["unaware", "problem_aware", "solution_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["4:5"],
        "tags": ["native", "ugly-ad", "post-it", "organic", "feed-blend", "handwritten"],
        "template_prompt": 'Use the attached images as brand reference. Match the exact [PRODUCT DESCRIPTION] precisely. Create: a lifestyle product photo set in [REAL-LIFE SETTING] with [LIGHTING DESCRIPTION] and a naturally blurred background showing [BACKGROUND DETAILS]. Frame is very slightly off-center — product not perfectly centered, feels found rather than composed. Slight natural sensor grain consistent with a phone camera. Center of frame: [FULL PRODUCT DESCRIPTION] sitting on [SURFACE], slightly angled toward the viewer. [SCATTERED SURFACE DETAIL] on the surface around the base of the product. Stuck directly onto the front face of the product: a [POST-IT COLOR — yellow default] square post-it note, slightly crooked. Realistic paper texture with a horizontal crease. Subtle curl at bottom-right corner. Held at the top by a small piece of [TAPE COLOR] tape. Handwritten in thick black marker-style lettering, imperfect and uneven, lowercase: "[LINE 1]" "[LINE 2]" "[LINE 3]" "[LINE 4 — optional]". No brand logo in frame. Brand identity carried by the product packaging. [MOOD]. 4:5 aspect ratio.',
    },
]

# Write all templates
for t in TEMPLATES:
    t["source"] = SOURCE
    t["platforms"] = ["meta", "tiktok"]
    filename = f"{t['id'].replace('cooper-', '')}.yaml"
    path = OUTPUT_DIR / filename
    with open(path, "w", encoding="utf-8") as f:
        yaml.dump(t, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
    print(f"  Created: {path}")

print(f"\nDone! {len(TEMPLATES)} Cooper templates imported to {OUTPUT_DIR}")
