"""Import 22 selected prompts from 0aicoder0/Ultimate-Nano-Banana-Pro-Collection.

Source: https://github.com/0aicoder0/Ultimate-Nano-Banana-Pro-Collection
Run: python scripts/import_ultimate_selected.py
"""

from pathlib import Path
import yaml

OUTPUT_DIR = Path("prompts/library/nanobana")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SOURCE = "0aicoder0/Ultimate-Nano-Banana-Pro-Collection"

TEMPLATES = [
    {
        "id": "uc-2.3-beauty-product-macro",
        "name": "Beauty Product Macro Shot",
        "category": "product-hero",
        "description": "Editorial beauty macro — model holds product close to camera with dramatic foreshortening. Product tack-sharp, face in soft bokeh. White seamless background.",
        "product_types": ["beauty", "cosmetics", "accessories"],
        "audience_fit": ["product_aware", "most_aware"],
        "funnel_stage": "conversion",
        "aspect_ratios": ["3:4"],
        "tags": ["beauty", "macro", "product-hero", "editorial", "close-up", "hands"],
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nUltra-photoreal editorial beauty macro shot. A [PERSON DESCRIPTION matching target demographic] holds [YOUR PRODUCT] extremely close to the camera with dramatic perspective. The product is the main focus (tack sharp), while the face is softly out of focus behind it. Pure white seamless background.\n\nCamera: wide-close macro perspective (24-35mm feel), f/2.0-f/2.8, shallow DOF.\nLighting: clean high-key studio, soft shadows, crisp specular highlights on product.\nSubject: [HAIR DESCRIPTION], [MAKEUP coordinating with product color].\nHands: both hands framing and holding the product close to lens. [NAIL COLOR matching product]. Perfect hands, five fingers each.\nProduct: [EXACT PRODUCT DESCRIPTION from reference images — shape, color, label text, branding].\n\nQuality: ultra realistic skin texture, no plastic smoothing, natural eye catchlights, product label readable and correct, high-end magazine beauty advertising look.\n\n3:4 aspect ratio.",
    },
    {
        "id": "uc-2.4-beauty-contact-sheet-3x3",
        "name": "Beauty Product 3x3 Contact Sheet",
        "category": "campaign-set",
        "description": "3x3 grid collage of 9 beauty panels — one model in varied poses with a product. Pure white background. Magazine campaign quality.",
        "product_types": ["beauty", "cosmetics"],
        "audience_fit": ["product_aware", "most_aware"],
        "funnel_stage": "conversion",
        "aspect_ratios": ["4:5"],
        "tags": ["3x3-grid", "beauty", "campaign", "contact-sheet", "multi-panel"],
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nUltra-photoreal beauty campaign contact sheet on pure white seamless background. A 3x3 grid collage of nine panels featuring ONE [PERSON DESCRIPTION] with [HAIR DESCRIPTION]. The model has [BUILD DESCRIPTION] and an attractive high-fashion look. Skin is luminous with realistic texture. Makeup: [MAKEUP DESCRIPTION coordinating with product].\n\nProduct: [YOUR PRODUCT — exact description]. The product stays consistent across all panels.\n\n9 Panel variety:\n1) Model holds product horizontally over eyes; lips puckered\n2) Close-up applying/using the product; brand name visible\n3) Model laughing wide-mouth; product held near face\n4) Beauty angle portrait holding product near chin; confident gaze\n5) Extreme close-up smile with teeth; product held lightly\n6) Wink + playful expression; product visible\n7) Using product again with elegant hand pose\n8) Kissy face wink; cheek highlight strong\n9) Tight crop smile; crisp detail\n\nLighting: beauty studio — large soft key + fill + subtle rim, bright and clean. Camera: 85mm beauty lens, f/8. No watermark, no extra logos.\n\n4:5 aspect ratio.",
    },
    {
        "id": "uc-2.6-luxury-product-grid",
        "name": "Luxury Product Photography 3x3 Grid",
        "category": "campaign-set",
        "description": "3x3 grid of high-end commercial product shots — 9 different creative scenarios from hero still life to surreal fusion. Maintains identical product fidelity across all panels.",
        "product_types": ["beauty", "luxury", "beverage", "any"],
        "audience_fit": ["product_aware", "most_aware"],
        "funnel_stage": "conversion",
        "aspect_ratios": ["3:4"],
        "tags": ["luxury", "3x3-grid", "product", "campaign", "multi-concept"],
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nA 3x3 image grid of high-end commercial product shots showing [YOUR PRODUCT] in nine different creative scenarios. Each frame maintains identical product fidelity.\n\n1. Hero Still Life — product on [ACCENT MATERIAL like marble/velvet/wood] pedestal, dramatic studio lighting\n2. Extreme Macro Detail — ultra-close on product texture, material quality, label detail\n3. Dynamic Interaction — [LIQUID/SPLASH/MOVEMENT element], frozen mid-action\n4. Minimal Sculptural — product on geometric shapes, clean shadows, gallery aesthetic\n5. Floating Elements — product suspended with [RELATED ELEMENTS like petals/drops/ingredients] orbiting\n6. Sensory Close-up — close texture shot emphasizing material and finish\n7. Color-Driven Scene — product on [BRAND COLOR] backdrop with matched props\n8. Symbolic Abstraction — conceptual scene connecting product to its benefit\n9. Surreal Fusion — product merged with an unexpected natural element\n\nHyperreal cinematic quality, ultra-sharp focus, consistent product rendering across all panels.\n\n3:4 aspect ratio.",
    },
    {
        "id": "uc-2.7-vintage-box-retro",
        "name": "Vintage Product Box & CD-ROM (Retro)",
        "category": "creative",
        "description": "Transform any brand/website into a physical 1995-era software box with CD-ROM. Nostalgic retro packaging aesthetic.",
        "product_types": ["saas", "any"],
        "audience_fit": ["unaware", "problem_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["1:1", "4:5"],
        "tags": ["retro", "vintage", "1995", "creative", "packaging", "nostalgic", "scroll-stopper"],
        "template_prompt": "[YOUR BRAND/WEBSITE] turned into a product box with a CD-ROM as if it was from [ERA — default 1995]. The box features era-appropriate design with [BRAND COLORS], [BRAND NAME] prominently displayed, and [TAGLINE or PRODUCT DESCRIPTION] on the front. Retro packaging aesthetics, Windows 95/Mac OS era graphic design. The CD-ROM sits beside the box, visible and matching the brand. [SURFACE — on carpet / on desk / on shelf]. Nostalgic, authentic vintage tech product photography.\n\n1:1 aspect ratio.",
    },
    {
        "id": "uc-2.8-beverage-can-hero-splash",
        "name": "Beverage Can Hero with Crown Splash",
        "category": "product-hero",
        "description": "Ultra-realistic luxury beverage can photography — condensation droplets, dramatic crown splash behind, fruit and ice at base. Dark themed.",
        "product_types": ["beverage", "food"],
        "audience_fit": ["product_aware", "most_aware"],
        "funnel_stage": "conversion",
        "aspect_ratios": ["2:3"],
        "tags": ["beverage", "can", "splash", "hero", "luxury", "condensation", "dark-theme"],
        "template_prompt": "Use the attached images as brand reference. Match the exact product design, label, and colors precisely.\n\nUltra-realistic luxury [YOUR PRODUCT — beverage can/bottle] product photography. The container is centered in frame, covered in ultra-fine condensation droplets with realistic refraction. A dramatic crown-shaped splash of [LIQUID COLOR matching flavor] erupts upward from behind the product.\n\nBackground: [DARK COLOR matching product theme] gradient.\nBase: fresh [FRUIT/INGREDIENT TYPE] pieces and crystalline ice scattered at the base.\nCamera: macro lens focus on can and droplets, 8K resolution.\nLighting: studio, cinematic, high detail, specular highlights on metallic surface.\nProduct label: [BRAND NAME] and [FLAVOR TEXT] must be crisp, readable, and correctly spelled.\n\n2:3 aspect ratio.",
    },
    {
        "id": "uc-2.10-seasonal-product-environment",
        "name": "Seasonal Product in Natural Environment",
        "category": "product-hero",
        "description": "Product placed in a themed natural environment matching its flavor/season. Bottle interacts with surroundings through condensation, splashes, scattered ingredients.",
        "product_types": ["beverage", "food", "beauty"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["9:16"],
        "tags": ["seasonal", "environmental", "product", "nature", "cinematic", "atmospheric"],
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nPhotorealistic advertising shot of [YOUR PRODUCT] placed in [NATURAL ENVIRONMENT matching product theme — e.g. snowy mountain clearing / tropical beach / autumn forest / spring garden]. The product sits on [NATURAL SURFACE — mossy rock / sandy ground / fallen leaves / grass].\n\nSurrounding elements: [MATCHING INGREDIENTS/FRUITS] scattered naturally around the base. Condensation on the product surface. [ATMOSPHERIC ELEMENTS — morning mist / snow falling / golden hour light / cherry blossoms].\n\nCamera: cinematic close-up, hyper-realistic textures, slight lens flare.\nLighting: natural environment lighting — [LIGHT DESCRIPTION matching scene].\nColor scheme: [DOMINANT COLORS of the scene].\nMood: [MOOD — refreshing / cozy / vibrant / serene].\n\nProduct label clearly visible and readable. Magazine-quality advertising photography.\n\n9:16 aspect ratio.",
    },
    {
        "id": "uc-2.14-smartphone-surreal-product",
        "name": "Smartphone Surreal Product Ad (Trans-Dimensional)",
        "category": "creative",
        "description": "Surreal composite — a real hand pours/interacts with a product that crosses from the physical world into a phone screen. Trans-dimensional effect.",
        "product_types": ["beverage", "food", "any"],
        "audience_fit": ["unaware", "problem_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["3:4", "4:5"],
        "tags": ["surreal", "smartphone", "creative", "scroll-stopper", "mixed-reality"],
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nHyper-realistic surreal composite: a real human hand [ACTION — pours / holds / presents] [YOUR PRODUCT] that interacts with a person displayed on a smartphone screen. The [PRODUCT ELEMENT — liquid / item / effect] crosses from the physical realm into the digital realm, creating a trans-dimensional effect.\n\nThe phone lies flat on a [SURFACE — wooden table / marble counter / studio surface]. On the phone screen: a [PERSON DESCRIPTION] in [SETTING — kitchen / cafe / outdoor] reaching toward the product.\n\nMiniature [RELATED PROPS — cups / fruit / ingredients] scattered on the table around the phone.\n\nCamera: high-angle looking down, tight framing on phone and hand.\nLighting: warm natural light, soft diffused volumetric shadows.\nQuality: photorealistic, seamless blend between real and digital elements.\n\n4:5 aspect ratio.",
    },
    {
        "id": "uc-4.6-flat-lay-social-ad",
        "name": "Flat Lay Social Media Ad (Instagram Post Style)",
        "category": "social-proof",
        "description": "Top-down flat lay of people around a table, designed to look like an Instagram post. Physical table has white strips mimicking IG UI elements.",
        "product_types": ["food", "beverage", "any"],
        "audience_fit": ["unaware", "problem_aware"],
        "funnel_stage": "awareness",
        "aspect_ratios": ["1:1", "4:5"],
        "tags": ["flat-lay", "overhead", "social-media", "instagram", "creative", "group"],
        "template_prompt": "Use the attached images as brand reference.\n\nUltra-wide-angle top-down flat lay photograph of [NUMBER — 2-4] people sitting around a square dining table, designed to look like an Instagram post. The table has physical white strips at top and bottom edges mimicking Instagram UI (profile picture circle, [USERNAME], verified tick at top; heart/comment/share icons at bottom).\n\nTable center: painted [BRAND COLOR] with [YOUR PRODUCTS / FOOD ITEMS] arranged within it. People seated at each edge wearing [CLOTHING STYLE — casual / branded / coordinated], each [INTERACTING with the product — eating / holding / reaching].\n\nFloor: [FLOOR COLOR] creating visual separation.\nLighting: professional studio lighting with distinct drop shadows.\nMood: [MOOD — fun and social / premium / casual hangout].\n\nShot from directly overhead. Magazine-quality production.\n\n1:1 aspect ratio.",
    },
    {
        "id": "uc-6.1-post-workout-hydration",
        "name": "Post-Workout Hydration (Fitness Scene)",
        "category": "lifestyle",
        "description": "Woman on yoga mat after workout — wiping sweat, holding water bottle. Authentic gym selfie aesthetic with realistic post-exercise details.",
        "product_types": ["apparel", "beverage", "supplement", "fitness"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["9:16"],
        "tags": ["fitness", "gym", "workout", "lifestyle", "authentic", "ugc", "health"],
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nA [PERSON DESCRIPTION matching target demographic] sits on a yoga mat after a workout, wiping sweat with the back of one hand and holding [YOUR PRODUCT — water bottle / supplement / towel showing brand] in the other. Authentic gym selfie aesthetic.\n\nRealistic post-exercise details: flushed skin with natural sheen, [HAIR — messy ponytail with flyaways / headband], visible sweat on forehead and arms. Wearing [YOUR APPAREL PRODUCT or WORKOUT OUTFIT — sports bra and leggings / tank and shorts].\n\nSetting: modern gym studio with [EQUIPMENT — dumbbells / resistance bands / mirrors] blurred behind.\nCamera: smartphone front camera selfie, slightly above eye level.\nLighting: bright overhead LED gym lighting, even coverage.\nExpression: [EXPRESSION — accomplished smile / exhausted but happy / taking a breath].\n\n9:16 aspect ratio.",
    },
    {
        "id": "uc-6.4-gym-selfie-yoga-mat",
        "name": "Gym Mirror Selfie on Yoga Mat",
        "category": "ugc",
        "description": "Cross-legged on yoga mat, mirror selfie with phone. Realistic post-exercise details. Minimal modern gym environment.",
        "product_types": ["apparel", "fitness", "supplement"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["4:5", "9:16"],
        "tags": ["gym", "mirror-selfie", "yoga", "fitness", "ugc", "authentic"],
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nA [PERSON DESCRIPTION matching target demographic] sits cross-legged on a [COLOR] yoga mat taking a mirror selfie with smartphone after a workout. Realistic post-exercise details: flushed skin, natural sweat sheen, [HAIR — messy ponytail / headband].\n\nWearing [YOUR PRODUCT — exact description from product images]. [ADDITIONAL ITEMS — sneakers beside mat / water bottle / resistance bands in foreground].\n\nGym environment: minimal modern space with [EQUIPMENT — power rack / dumbbells / kettlebells] visible in mirror reflection. Large mirror wall.\n\nCamera: smartphone photography, moderate depth of field.\nLighting: bright natural indoor lighting, even illumination, soft shadows.\nExpression: [EXPRESSION — relaxed smile / taking a break / proud].\n\n4:5 aspect ratio.",
    },
    {
        "id": "uc-15.1-sports-team-photo",
        "name": "Sports Team / Group Photo",
        "category": "lifestyle",
        "description": "Indoor group photo of 2-4 people in matching outfits posing playfully. Team snapshot aesthetic. Focus on photography style and model posing.",
        "product_types": ["apparel", "fitness"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["9:16"],
        "tags": ["group", "team", "matching-outfits", "playful", "casual", "sports"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nIndoor [SETTING — gym / studio / hallway] team-style photo of [NUMBER] [PEOPLE DESCRIPTION matching target demographic] in matching [YOUR PRODUCT — exact description]. Each person has a distinct pose: [POSE 1 — standing with hands on hips], [POSE 2 — squatting / crouching playfully], [POSE 3 — back turned showing back of garment]. Expressions are [EXPRESSIONS — smiling, tongue out, playful].\n\nCasual celebratory team snapshot aesthetic.\n[TEAM TEXT or BRAND NAME] visible on [WALL / BANNER] behind them.\nFloor: [FLOOR TYPE — polished wood / gym floor / concrete].\n\nCamera: eye-level, sharp focus on subjects and text.\nLighting: indoor ambient, even frontal, soft with no harsh shadows.\n\n9:16 aspect ratio.",
    },
    {
        "id": "uc-15.2-holiday-bedroom-portrait",
        "name": "Seasonal / Holiday Bedroom Portrait",
        "category": "lifestyle",
        "description": "Person in themed clothing lying/lounging on bed. Seasonal decor in background. Warm intimate lighting. Focus on photography style.",
        "product_types": ["apparel", "fashion"],
        "audience_fit": ["product_aware", "most_aware"],
        "funnel_stage": "conversion",
        "aspect_ratios": ["9:16", "4:5"],
        "tags": ["seasonal", "holiday", "bedroom", "intimate", "cozy", "portrait"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nA [PERSON DESCRIPTION matching target demographic] in [YOUR PRODUCT — seasonal/themed clothing] lies on a bed with [LINEN COLOR] linens, propped on elbows in a [POSE — relaxed / pouting / playful] pose.\n\n[SEASONAL DECOR — Christmas garland lights and small tree / autumn leaves and candles / spring flowers / summer beach elements] in background.\n\nWarm indoor ambient lighting, vertical high-angle framing looking slightly down at subject. Intimate, cozy mood.\nExpression: [EXPRESSION — soft smile / playful pout / relaxed gaze].\nHair: [HAIR DESCRIPTION].\n\nVertical orientation. 9:16 aspect ratio.",
    },
    {
        "id": "uc-15.3-flash-portrait-seasonal",
        "name": "Flash Portrait with Seasonal Background",
        "category": "lifestyle",
        "description": "Candid flash portrait in home setting with seasonal decor. On-camera flash creates hard shadows mixed with warm ambient light. Authentic snapshot feel.",
        "product_types": ["apparel", "fashion"],
        "audience_fit": ["product_aware", "most_aware"],
        "funnel_stage": "conversion",
        "aspect_ratios": ["4:5"],
        "tags": ["flash", "candid", "seasonal", "home", "snapshot", "authentic"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nCandid portrait of a [PERSON DESCRIPTION matching target demographic] in [YOUR PRODUCT — sweater / hoodie / loungewear] posing with a [EXPRESSION — kissy face / laugh / peace sign / hands pressed to cheeks]. Shot with on-camera flash creating hard shadows and bright highlights, mixed with warm ambient [LIGHT SOURCE — Christmas tree lights / string lights / candles / lamp].\n\n[HOME SETTING — living room at night / cozy den / bedroom] with [DECOR — seasonal decorations / wall art / bookshelves] visible behind. Window [DETAIL — blinds reflecting flash / curtains].\n\nCamera: smartphone camera, wide aperture, fast shutter (flash), high ISO.\nHigh contrast between flash and ambient. Authentic candid snapshot feel.\n\n4:5 aspect ratio.",
    },
    {
        "id": "uc-16.1-studio-portrait-multi-panel",
        "name": "Studio Portrait Multi-Panel Collage",
        "category": "campaign-set",
        "description": "Multi-panel (3-4) studio portraits showing model in varied shots — macro, medium, full body. Ultra-photorealistic 8K. Seamless background.",
        "product_types": ["apparel", "fashion", "beauty"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["3:4", "4:5"],
        "tags": ["studio", "multi-panel", "portrait", "editorial", "beauty", "campaign"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nFour-panel collage of studio portraits showing a [PERSON DESCRIPTION matching target demographic — NO celebrity references] in [YOUR PRODUCT — exact outfit description]:\n\nPanel 1: Extreme close-up — [ACTION like eating a fruit / applying product / touching face], beauty macro detail\nPanel 2: Medium shot — thigh-up, [POSE — standing / seated / leaning], direct eye contact\nPanel 3: Full body — [POSE — seated on stool / standing / walking], showing complete outfit\nPanel 4: [ANGLE — side profile / three-quarter / over-shoulder], different perspective\n\nUltra-photorealistic 8K textures, dewy skin, [MAKEUP STYLE]. Seamless [BACKGROUND COLOR — off-white / cream / light gray] studio background.\nLighting: large diffuse softbox key + reflector fill, specular highlights on skin.\n\n3:4 aspect ratio.",
    },
    {
        "id": "uc-16.3-retro-room-portrait",
        "name": "Retro Room Portrait (Direct Flash)",
        "category": "lifestyle",
        "description": "Direct-flash portrait in a densely decorated room. 80s-90s film aesthetic with warm tungsten tones and bold flash contrast. Focus on photography style.",
        "product_types": ["apparel", "fashion"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["3:4", "4:5"],
        "tags": ["retro", "flash", "portrait", "room", "vintage", "film-aesthetic"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nDirect-flash portrait of a [PERSON DESCRIPTION matching target demographic] in a [ROOM THEME — retro gaming den / cozy reading nook / craft room / music room], seated on a [SEATING — couch / chair / floor cushion] holding [PROP — controller / book / drink / phone]. Wearing [YOUR PRODUCT — exact description] with [ACCESSORIES — headphones / hat / jewelry].\n\nShelves behind densely packed with [SHELF CONTENTS matching room theme — collectibles / books / records / plants]. [PLUSH TOY or DECOR ITEM] beside them.\n\nCamera: 35mm prime, f/2.0, ISO 400-800.\nLighting: strong direct on-camera flash + warm tungsten [AMBIENT SOURCE — desk lamp / string lights / neon sign] in background. Sharp shadow falloff. 80s-90s film aesthetic.\n\nLow eye-level perspective. Nostalgic, authentic feel.\n\n3:4 aspect ratio.",
    },
    {
        "id": "uc-16.7-couple-phone-selfie",
        "name": "Couple Portrait Through Phone Screen",
        "category": "lifestyle",
        "description": "Candid editorial mirror/phone selfie — couple visible through smartphone display. Phone fills most of frame. Warm cinematic lighting with subtle film grain.",
        "product_types": ["apparel", "fashion", "accessories", "jewelry"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["2:3"],
        "tags": ["couple", "phone-selfie", "candid", "editorial", "jewelry", "intimate"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nCandid editorial selfie taken through a smartphone interface. The phone fills most of the frame with realistic glass reflections and screen glare. Inside the display: a couple — [PERSON 1 DESCRIPTION] and [PERSON 2 DESCRIPTION] sit close together. [INTERACTION — one kisses the other's cheek / they lean heads together / arms around each other]. [EXPRESSION — playful smirk / genuine laugh / soft smile].\n\n[YOUR PRODUCT — jewelry / accessories / matching outfits] prominently displayed on the phone-holding hand or visible on the subjects.\n\nEnvironment inside phone: [SETTING — cafe / lounge / park bench / couch].\nCamera: iPhone-like candid shot, warm indoor cinematic, subtle analog film grain.\nLighting: warm tungsten + soft fill, faces tack sharp, background bokeh.\nHands and [JEWELRY/ACCESSORIES] prominently rendered.\n\n2:3 aspect ratio.",
    },
    {
        "id": "uc-16.8-landmark-travel-portrait",
        "name": "Travel Portrait at Famous Landmark",
        "category": "lifestyle",
        "description": "Person at famous landmark during blue hour/twilight. Gazing into distance with illuminated architecture behind. Shallow DOF, 35mm film grain aesthetic.",
        "product_types": ["apparel", "fashion", "accessories"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["3:4"],
        "tags": ["travel", "landmark", "twilight", "cinematic", "portrait", "golden-hour"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nA [PERSON DESCRIPTION matching target demographic] sits on a stone ledge at [LANDMARK — famous location / architectural site / scenic overlook] during [TIME — blue hour twilight / golden hour sunset / early morning]. [POSE — gazing into the distance with one hand running through hair / leaning forward with elbows on knees / looking over shoulder at camera].\n\nWearing [YOUR PRODUCT — exact description]. [ACCESSORIES — sunglasses on head / bag / watch].\n\nThe illuminated [LANDMARK] glows warm golden behind against a deep [SKY COLOR — blue evening / orange sunset / pink dawn] sky.\n\nCamera: portrait prime 50-85mm, f/2.8 shallow DOF, 8K resolution, subtle 35mm film grain.\nLighting: mixed cinematic — warm key on subject, warm tungsten on architecture, cool ambient from sky.\nMood: [MOOD — contemplative and aspirational / adventurous / peaceful].\n\n3:4 aspect ratio.",
    },
    {
        "id": "uc-16.9-relaxed-couch-portrait",
        "name": "Relaxed Loungewear Portrait on Couch",
        "category": "lifestyle",
        "description": "Person lounging on couch in branded clothing. Natural features visible. Modern living room with statement art. Influencer lifestyle aesthetic.",
        "product_types": ["apparel", "fashion", "loungewear"],
        "audience_fit": ["product_aware", "most_aware"],
        "funnel_stage": "conversion",
        "aspect_ratios": ["3:4", "4:5"],
        "tags": ["loungewear", "couch", "home", "lifestyle", "influencer", "relaxed"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nA [PERSON DESCRIPTION matching target demographic] lounges on a [COUCH COLOR] couch in [YOUR PRODUCT — exact loungewear / apparel description showing brand text/graphic]. Natural features visible: real skin texture, [NATURAL DETAILS — freckles / tan lines]. [POSE — reclining with one arm behind head / legs tucked / leaning on arm rest].\n\nModern living room with [WALL ART — statement art pieces / prints / gallery wall] and ambient lighting. [ROOM DECOR — plants / books / candles / throw pillows].\n\nCamera: 35-50mm portrait lens, low-medium ISO, sharp face with slight background DOF blur.\nLighting: soft diffused indoor mix of window light + warm [LIGHT SOURCE — wall sconce / lamp / candles].\nAesthetic: influencer lifestyle, 2000s digital camera vibe, hyper-detailed skin textures.\n\n4:5 aspect ratio.",
    },
    {
        "id": "uc-16.22-couple-holiday-portrait",
        "name": "Couple Holiday Portrait (Flash)",
        "category": "lifestyle",
        "description": "Candid flash photo of couple on floor with holiday decor. Authentic smartphone flash look with dim room and warm shadows.",
        "product_types": ["apparel", "fashion"],
        "audience_fit": ["product_aware", "most_aware"],
        "funnel_stage": "conversion",
        "aspect_ratios": ["3:4"],
        "tags": ["couple", "holiday", "flash", "candid", "christmas", "intimate", "authentic"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nCandid flash photo of a couple on the floor in front of a [HOLIDAY DECOR — decorated Christmas tree / Thanksgiving table / birthday setup]. [PERSON 1] in foreground holds [PROP — wine glass / mug / gift] and wears [YOUR PRODUCT — exact description]. [PERSON 2] behind wraps arm around them, wearing [COMPLEMENTARY OUTFIT].\n\nAuthentic smartphone flash look: bright on faces, dim room behind, warm shadows from [AMBIENT LIGHT — tree lights / candles / string lights], subtle grain.\n\n[GIFTS/DECOR — wrapped presents / party items / seasonal elements] in foreground.\nCozy [ROOM SETTING — living room / dining room].\n\nCamera: 28-35mm equivalent, smartphone/compact flash, slightly above eye level.\n\n3:4 aspect ratio.",
    },
    {
        "id": "uc-17.11-corset-blazer-outfit",
        "name": "Layered Fashion Portrait (City Night)",
        "category": "lifestyle",
        "description": "Fashion portrait with layered outfit against large windows showing city nightscape with bokeh lights. Glamour lighting with soft shadows.",
        "product_types": ["apparel", "fashion"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["3:4", "4:5"],
        "tags": ["fashion", "city-night", "glamour", "portrait", "layered-outfit", "bokeh"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nFashion portrait of a [PERSON DESCRIPTION matching target demographic] in [YOUR PRODUCT — exact outfit description, with layering details]. [OUTERWEAR — blazer / jacket / cardigan] draped over shoulders. Standing front-facing with direct eye contact.\n\nBackground: large glass windows showing [BLURRED BACKGROUND — city nightscape with bokeh lights / sunset skyline / rainy street]. Modern urban interior.\n\nCamera: medium shot (waist-up), eye-level.\nLighting: glamour lighting — soft indoor ambient mixed with cool outdoor lighting through windows. Soft shadows, highlights on hair and shoulders.\nColor palette: [DOMINANT COLORS from outfit and brand].\n\n4:5 aspect ratio.",
    },
    {
        "id": "uc-17.22-vintage-street-style-collage",
        "name": "Vintage Street Style Multi-Panel Editorial",
        "category": "campaign-set",
        "description": "3-frame editorial poster collage — reflective window shot, ultra-wide street portrait, overhead selfie. Includes translucent UI overlay graphic. Retro analog-digital fusion.",
        "product_types": ["apparel", "fashion", "accessories"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["9:16"],
        "tags": ["vintage", "street-style", "multi-panel", "editorial", "collage", "retro"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nEditorial poster-style multi-panel collage (3 frames) showing a [PERSON DESCRIPTION matching target demographic] in [YOUR PRODUCT — exact outfit description] with [ACCESSORIES — sunglasses / hat / earphones / watch].\n\nFrame 1: [SHOT TYPE — reflective window / mirror / glass] shot — subject visible through reflection, [URBAN SETTING] behind.\nFrame 2: Ultra-wide [SETTING — cobblestone street / sidewalk / park path] portrait, full body, dramatic perspective.\nFrame 3: Overhead selfie — subject looking up at camera, holding [PROP — drink / phone / bag].\n\nOptional: translucent [UI OVERLAY — music player / social media notification / text message] graphic element overlaid on one panel.\n\nColor palette: [DOMINANT COLORS — warm amber / cool blue / muted earth tones].\nOvercast natural lighting + architectural reflections. Retro analog-digital fusion aesthetic.\n\n9:16 aspect ratio.",
    },
    {
        "id": "uc-17.24-beauty-routine-3x3-grid",
        "name": "Beauty Routine 3x3 Lifestyle Grid",
        "category": "campaign-set",
        "description": "3x3 grid showing a beauty/getting-ready routine across 9 panels — mirror application, flat lays, close-ups, portraits. Luxury setting with natural daylight.",
        "product_types": ["beauty", "jewelry", "accessories", "apparel"],
        "audience_fit": ["solution_aware", "product_aware"],
        "funnel_stage": "consideration",
        "aspect_ratios": ["4:5", "1:1"],
        "tags": ["3x3-grid", "beauty-routine", "getting-ready", "lifestyle", "luxury", "jewelry"],
        "key_value": "Photography style and model posing — not background/setting.",
        "template_prompt": "Use the attached images as brand reference. Match the exact product design precisely.\n\nA 3x3 grid collage showing a [PERSON DESCRIPTION matching target demographic]'s beauty/getting-ready routine across nine panels. [HAIR DESCRIPTION]. Wearing [YOUR PRODUCT — outfit visible across panels].\n\nPanel 1: Applying makeup in a lit vanity mirror, [COSMETIC PRODUCTS] on counter\nPanel 2: Flat lay overhead — [YOUR PRODUCT / ACCESSORIES] arranged on [SURFACE — marble / silk / wood]\nPanel 3: Putting on [ACCESSORY — earrings / necklace / bracelet] near a window, natural light\nPanel 4: Extreme close-up of [ACCESSORY] on [BODY PART — ear / wrist / neck]\nPanel 5: Side profile portrait, [EXPRESSION — serene / contemplative]\nPanel 6: Waist-up portrait, [POSE — adjusting outfit / looking at camera]\nPanel 7: Touching hair, [EXPRESSION — gentle smile], backlit\nPanel 8: Laughing in mirror reflection, warm and candid\nPanel 9: Flat lay of [PRODUCTS / ACCESSORIES] on [FABRIC — silk cloth / linen]\n\nSetting: [LOCATION — luxury hotel suite / modern bathroom / bedroom vanity].\nLighting: mix of natural daylight and warm artificial vanity lighting.\nConsistent outfit and accessories across all panels.\n\n4:5 aspect ratio.",
    },
]

for t in TEMPLATES:
    t["source"] = SOURCE
    t["platforms"] = ["meta", "tiktok"]
    filename = f"{t['id']}.yaml"
    path = OUTPUT_DIR / filename
    with open(path, "w", encoding="utf-8") as f:
        yaml.dump(t, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
    print(f"  Created: {path}")

print(f"\nDone! {len(TEMPLATES)} Ultimate Collection prompts imported to {OUTPUT_DIR}")
