"""Creative Matrix — Pydantic schemas.

A creative matrix is the tactical bridge between briefs (high-level strategy)
and image/video generation (executional). It is a 4-tab structure where each
row is a self-contained, buildable creative seed enriched with format, psychology,
and a trending-ad match.

Tabs:
    pain_vs_competitor   negative gaps mined from competitor research
    what_they_love       positive triggers that competitors solve well
    wishes_gaps          white-space — what customers wish existed
    hook_angles          ready-to-shoot hook executions

Every row carries a common backbone — `format_fit`, `static_treatment`,
`psychology_trigger`, plus the trending match — so the system can treat any row
from any tab as a buildable unit downstream.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, field_validator

from models.avatar import HEURISTIC_NAMES

# ─── Picklist vocabularies ──────────────────────────────────────────────────


class MatrixTab(str, Enum):
    PAIN_VS_COMPETITOR = "pain_vs_competitor"
    WHAT_THEY_LOVE = "what_they_love"
    WISHES_GAPS = "wishes_gaps"
    HOOK_ANGLES = "hook_angles"


SOURCE_TYPES: frozenset[str] = frozenset({
    "reddit",
    "amazon",
    "trustpilot",
    "tiktok_comments",
    "ig_comments",
    "youtube_comments",
    "vertical_site",     # e.g. acne.org, MakeupAlley, Influenster
    "onsite_reviews",    # brand's own website reviews
    "news",
    "voc_corpus",
    "other",
})


FORMAT_FIT_VALUES: frozenset[str] = frozenset({
    "us-vs-them",
    "headline",
    "before-after",
    "ingredient-callout",
    "screenshot-review",
    "quote-pull",
    "meme",
    "carousel",
    "editorial",
    "features-benefits",
    "facts-stats",
    "media-press",
    "promotion-discount",
    "ugc-static",
    "video-only",
})


# ─── Trending sub-models ────────────────────────────────────────────────────


class TrendingMatch(BaseModel):
    """One trending-ad mechanic mapped to this row.

    `format_id` points back at an entry in trending_formats.yaml so the operator
    can pull the full recipe. `concept` and `execution` are LLM-generated for
    this specific row — they are how the trending mechanic should be applied
    given this row's strategic seed.
    """

    concept: str = Field(description="Trending-ad mechanic (e.g. 'ingredient receipt')")
    execution: str = Field(
        description="Concrete shoot/render direction — what to actually build "
        "for this row, in 1-4 sentences"
    )
    format_id: str = Field(
        default="",
        description="ID from trending_formats.yaml. Empty if the LLM proposed a "
        "trending mechanic not yet catalogued — operator should consider adding it.",
    )


class TrendingNext(BaseModel):
    """A second trending-ad idea built on the same psychological principle as
    the row's primary execution, but using a different mechanic.

    Lazily generated by default (only when --next is invoked) so we don't burn
    LLM cost on rows the operator never picks up.
    """

    idea: str = Field(description="Short name of the next-idea mechanic")
    principle: str = Field(
        description="Why this idea ties back to the same psychology_trigger as the row"
    )
    execution: str = Field(description="Concrete shoot/render direction")
    generated: str = Field(
        default="eager",
        description="'eager' if produced at matrix-build time, 'lazy' if filled later",
    )

    @field_validator("generated")
    @classmethod
    def _valid_generated(cls, v: str) -> str:
        if v not in {"eager", "lazy"}:
            raise ValueError(f"generated must be 'eager' or 'lazy', got '{v}'")
        return v


# ─── Row model ──────────────────────────────────────────────────────────────


class MatrixRow(BaseModel):
    """One row of the creative matrix.

    Tab-specific fields are optional — the generator populates only the fields
    relevant to the row's tab. The common backbone (format_fit, static_treatment,
    psychology_trigger, trending_match) is always present on a fully-generated row.
    """

    id: str = Field(description="Stable identifier, e.g. 'pain-001', 'love-014'")
    tab: MatrixTab

    # ─── Tab 1 (pain_vs_competitor) ─────────────────────────────────────────
    complaint: str = Field(default="", description="The specific complaint")
    our_advantage: str = Field(default="", description="Brand's edge against this complaint")
    positioning_angle: str = Field(default="", description="Ad-ready angle")

    # ─── Tab 2 (what_they_love) ─────────────────────────────────────────────
    emotional_trigger: str = Field(
        default="", description="The thing competitors solve well that hooks customers"
    )
    hook_or_angle_to_amplify: str = Field(
        default="", description="How we piggyback on the positive sentiment"
    )

    # ─── Tab 3 (wishes_gaps) ────────────────────────────────────────────────
    wished_product: str = Field(default="", description="What they wish existed")
    real_frustration: str = Field(
        default="", description="The underlying frustration behind the wish"
    )
    script_or_static_opportunity: str = Field(
        default="", description="Concrete creative opportunity unlocked by the wish"
    )

    # ─── Tab 4 (hook_angles) ────────────────────────────────────────────────
    hook_angle: str = Field(default="", description="The opening line")
    tactic: str = Field(default="", description="Hook tactic / mechanic")
    story_setup: str = Field(default="", description="The story or setup beats")
    why_it_works: str = Field(default="", description="Why this hook converts")

    # ─── Common to tabs 1/2/3 ───────────────────────────────────────────────
    source_type: list[str] = Field(
        default_factory=list, description="Where the insight came from"
    )
    what_people_say: str = Field(
        default="", description="7-10 word verbatim-flavoured summary of customer voice"
    )

    # ─── Bridge layer — present on every fully-generated row ────────────────
    format_fit: list[str] = Field(
        default_factory=list,
        description="Best-fit visual formats from FORMAT_FIT_VALUES",
    )
    static_treatment: str = Field(
        default="",
        description="Image-ad direction (sibling to script/story_setup). Empty when "
        "format_fit is video-only.",
    )
    psychology_trigger: str = Field(
        default="",
        description="One of the 9 canonical heuristics from HEURISTIC_NAMES. The join "
        "key between this row and any trending_next lookup.",
    )

    # ─── Trending integration ───────────────────────────────────────────────
    trending_match: TrendingMatch | None = Field(
        default=None,
        description="Primary trending-ad match. Always populated on a fully-generated "
        "row at standard/wide tiers; absent on lean unless explicitly refreshed.",
    )
    trending_next: TrendingNext | None = Field(
        default=None,
        description="Second trending idea built on the same psychology_trigger but a "
        "different mechanic. Eager at standard/wide; lazy at lean (populate via "
        "`adc matrix --row <id> --next`).",
    )

    @field_validator("source_type")
    @classmethod
    def _valid_source_types(cls, v: list[str]) -> list[str]:
        bad = [s for s in v if s not in SOURCE_TYPES]
        if bad:
            raise ValueError(
                f"Unknown source_type(s) {bad}. Must be from {sorted(SOURCE_TYPES)}"
            )
        return v

    @field_validator("format_fit")
    @classmethod
    def _valid_format_fit(cls, v: list[str]) -> list[str]:
        bad = [f for f in v if f not in FORMAT_FIT_VALUES]
        if bad:
            raise ValueError(
                f"Unknown format_fit value(s) {bad}. Must be from {sorted(FORMAT_FIT_VALUES)}"
            )
        return v

    @field_validator("psychology_trigger")
    @classmethod
    def _valid_psychology_trigger(cls, v: str) -> str:
        # Allow empty — the LLM may legitimately decline to assign one on
        # ambiguous rows. But if set, it must be canonical.
        if v and v not in HEURISTIC_NAMES:
            raise ValueError(
                f"Unknown psychology_trigger '{v}'. Must be one of: {sorted(HEURISTIC_NAMES)}"
            )
        return v


# ─── Top-level matrix container ─────────────────────────────────────────────


class CreativeMatrix(BaseModel):
    client: str
    generated_at: str = Field(description="ISO-8601 timestamp of the build")
    matrix_version: int = 1
    trending_source: str = Field(
        default="trending_formats.yaml",
        description="What library trending_match references resolve against",
    )
    research_sources_used: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Tiered map of source platforms actually consulted, e.g. "
        "{tier_1: [reddit, amazon], tier_3: [tiktok_comments]}",
    )
    tier: str = Field(
        default="standard",
        description="Generation tier: 'lean' (trending_match only), "
        "'standard' (match + next), 'wide' (match + 2 alternates)",
    )

    pain_vs_competitor: list[MatrixRow] = Field(default_factory=list)
    what_they_love: list[MatrixRow] = Field(default_factory=list)
    wishes_gaps: list[MatrixRow] = Field(default_factory=list)
    hook_angles: list[MatrixRow] = Field(default_factory=list)

    def all_rows(self) -> list[MatrixRow]:
        return (
            self.pain_vs_competitor
            + self.what_they_love
            + self.wishes_gaps
            + self.hook_angles
        )

    def find_row(self, row_id: str) -> MatrixRow | None:
        for r in self.all_rows():
            if r.id == row_id:
                return r
        return None

    def replace_row(self, row: MatrixRow) -> None:
        """Replace a row in place by id. Raises KeyError if not found."""
        bucket = getattr(self, row.tab.value)
        for i, existing in enumerate(bucket):
            if existing.id == row.id:
                bucket[i] = row
                return
        raise KeyError(f"Row {row.id} not found in tab {row.tab.value}")
